### ISSUE TITLE
Add Android SDK documentation for Xamarin and Cordova

### ISSUE THREAD

**Issue by jkernech** [dialonce/dialonce.github.io#9]

**Comment by CAMOBAP795** [comment]
In progress

**Comment by CAMOBAP795** [comment]
TODO
 - [ ] Update https://github.com/dial-once/sdk-mono/blob/master/README.md (remove user-level documentation)
 - [ ] Update https://github.com/dial-once/sdk-cordova/blob/master/README.md (remove user-level documentation)

**Comment by CAMOBAP795** [comment]
Done
